### ISSUE TITLE
Poor style: Please simplify this boolean result

### ISSUE THREAD

**Issue by marcelvaldez** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#139]
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/commit/8ffc28827be55b3977143a57f55c6eef94aab366#commitcomment-6186767

How did that pass code review?
We need to reassess the code review process. 
I suggest creating an online Pull Request Accepting System, where each pull request should be vetted by the Tech Lead, Scrum Master, Documentation Writer, Product Owner and QA Lead.

We also need a meeting for each pull request where they are reviewed step-by-step by these 5 people + Developer

**Comment by Mikkeren** [comment]
I will close this issue, since one of our senior developers have solved this, and we will make sure to re-evaluate our code review process on our next monthly meeting, to ensure that this will not happen again.
