### ISSUE TITLE
Poor style: Improve naming

### ISSUE THREAD

**Issue by marcelvaldez** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#140]
https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/commit/8ffc28827be55b3977143a57f55c6eef94aab366#commitcomment-6186829

Poor naming, please correct.

Again, how did this pass code review? Please read code review improvement suggestion in https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/issues/139#issue-32649348

**Comment by Mikkeren** [comment]
I will close this issue, since one of our senior developers have solved this, and we will make sure to re-evaluate our code review process on our next monthly meeting, to ensure that this will not happen again.
