### ISSUE TITLE
Poor style in interface definition

### ISSUE THREAD

**Issue by d53dave** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#167]
Interfaces and their methods are public by default, so public interface A { public void B() } should be interface A { void B() }.

**Comment by Mikkeren** [comment]
Since our developers are from varying cultures and have a variety of different setups, we cannot rely on defaults for any declarations.
This is specified in the company coding guidelines, but I am afraid these are confidential and as such, I cannot share any more information.
