### ISSUE TITLE
Why Java?

### ISSUE THREAD

**Issue by Pacerier** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#190]
Why Java?

**Comment by Dmitry-Me** [comment]
What other proved language has Enterprise Edition?

**Comment by davidzchen** [comment]
COBOL

**Comment by Dmitry-Me** [comment]
@davidzchen Good, but is it possible to craft an application with Best Practices Enterprise Grade Architecture in COBOL?

**Comment by Pacerier** [comment]
Scala is way more enterprisy than Java.

**Comment by emiln** [comment]
It does not currently seem feasible or even desirable to move FizzBuzzEnterpriseEdition to a different language or platform. I remain unconvinced that any of the mentioned suggestions are as battle-hardened, widely supported, popular among developers, and enjoy an equally impressive assortment of available Enterprise libraries compared to Java. While COBOL is not a bad suggestion in its own right, there seems little to no benefit in switching at this point and we are already heavily invested in tooling, staffing, and infrastructure for Java.
