### ISSUE TITLE
Does not run

### ISSUE THREAD

**Issue by javaJake** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#196]
I double-click and nothing happens.

Windows 95
21/m

**Comment by DizzyThermal** [comment]
Windows 98 SE
Pentium III Xeon

I concur with @javaJake 

FTR, I changed double-click timeout speed, same results

**Comment by emiln** [comment]
While I appreciate the inconvenience you are experiencing I need to stress the fact that this is an Enterprise-grade software solution. It would not be seemly if anybody could just download and run our product. Even as I write, steps are being taken to ensure that our product will only run on certain Microsoft™-certified partners' servers, that running it at all requires signing a Non-Disclosure Agreement, and that the whole ordeal will involve countless dozens of emails with hundreds of CC'ed stakeholders with obstinate opinions on Security by Petty Bureaucracy. Only by enduring such a crucible will potential users convince us of their worthiness, and only so will we consider the leniency of bestowing upon them the right to run our software. This right may be revoked for opaque and undisclosed reasons at any point, of course.

I hope this has cleared up any questions about actually running Enterprise-grade software.
