### ISSUE TITLE
This needs to be dockerized

### ISSUE THREAD

**Issue by atedja** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#203]
Need a Dockerfile for this enterprise solution.

**Comment by Mikkeren** [comment]
We have discussed this with operations and at present our setup will not support docker as it is still in an internal testing phase, and operations need to do a full writeup of any new technology before it is put in production.
Adding docker support is a wish from our engineering team, but the business does not see the value in it at this point in time. So while operations is working on the setup, there are no plans to move FizzBuzz Enterprise Edition™ to docker for now.
