### ISSUE TITLE
-1 not enough jQuery

### ISSUE THREAD

**Issue by gengkev** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#215]

**Comment by emiln** [comment]
You will be pleased to learn that we are now undertaking the creation of a website to enhance our online presence. *jQuery* is one of several contending web technologies currently being appraised for inclusion, and I trust you will be fully satisfied with our decisions regarding the technology stack. See #217 for additional information and be sure to chime in with your thoughts.

**Comment by gengkev** [comment]
I appreciate your taking the initiative to enhance the online presence of _FizzBuzz Enterprise Edition_ through this undertaking and trust that your efforts will redeem the esteemed reputation of _Enterprise Quality Coding_.
