### ISSUE TITLE
Using Github

### ISSUE THREAD

**Issue by kmooney** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#30]
This repository is hosted on Github, which is fine for individuals who want to play around but is inappropriate for serious businesses.  Please move this repository to Perforce.

**Comment by emiln** [comment]
After two years of careful deliberation on the matter we have arrived at a conclusion. The initial submission of this issue sparked a heated debate at the office, which turned into several preliminary meetings to identify key stakeholders. With the stakeholders identified we called for a series of meetings to appoint the committee to analyze our current solution and another committee to appraise existing alternatives for VCSs and the hosting of such. After a full year of investigation the committees submitted their reports, which were eventually reviewed by our BoD. The reports eventually became a series of PDCAs that were approved and funded through our Change Management Process and work began to bring the PDCAs to fruition, which would bring about our new VCS strategy.

Business then suddenly changed their minds about the priority of the project ant it is now stranded indefinitely. I am closing the issue as no resolution is expected .
