### ISSUE TITLE
fuzzing

### ISSUE THREAD

**Issue by joriszwart** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#320]
This definitely needs to be fuzzed with an enterprise level fuzzer. Who wants to fund?

**Comment by eriknyquist** [comment]
A FizzBuzz Fuzz Fund Task Force may be required to move forward on this.

**Comment by claui** [comment]
I have checked with IT. They have recently procured a company-wide license for _Fuzz Business_ and that tool will be mandatory going forward.

All we need to integrate Fuzz Business is to convert the FizzBuzz project to J2SE release 1.4 or earlier. Can we do that?

**Comment by josephtoles** [comment]
We should register the domain name before this goes viral. How's fizzbuzzfuzz.biz sound?

**Comment by claui** [comment]
Deborah from PR just told me this sounds great! She also suggests that we charter a bus to promote the new domain name.

**Comment by joriszwart** [comment]
Much talk, no code!
