### ISSUE TITLE
Javadoc missing

### ISSUE THREAD

**Issue by alokmishra** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#36]
Not acceptable without proper documentation.

**Comment by jarnaiz** [comment]
vote up!

**Comment by emiln** [comment]
The JavaDoc will not be available until after you have signed our proprietary Non-Disclosure Agreement (NDA). I'm afraid I can't disclose or discuss the agreement, the contractual content, or anything else related to documentation or the NDA until you've signed it blindly and faithfully.

If this causes any difficulty in the use of our FizzBuzzEnterpriseEdition solution or you have difficulties signing the NDA, be sure to reach out to our support staff. They are on call 24 hours a day and their contact information will be made available after signing the NDA.
