### ISSUE TITLE
Project Halted due to Funding

### ISSUE THREAD

**Issue by gdbjohnson** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#405]
Project has been halted due to lack of funds for the provided CAPEX account.  All allocated CAPEX has been used.  Please provide a new funding code to allocate resourcing costs to.

**Comment by emiln** [comment]
Due to a clever sleight of hand we've managed to hide further development under a poorly managed OPEX account. All is well again.

**Comment by gdbjohnson** [comment]
Let me guess.  Sales?

**Comment by vikramdurai** [comment]
Close issue since issue seems to have had no development over past 6months. We don't leave food out in the open to rot.

**Comment by gdbjohnson** [comment]
I guess I'll close it.  Project overruns and what not...
