### ISSUE TITLE
Why does not this product have any licence?

### ISSUE THREAD

**Issue by liamkernighan** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#417]
Without licence everyone can use that code, clone it or modify with no any consequences. Every enterprise software should be protected with appropriate licence. Please add MIT, Apache or Commercial licence to the code.

**Comment by Mikkeren** [comment]
I am afraid you are misinformed on this matter.

The fact that no license is present in the code does not mean you are allowed to do anything you want, but in fact means the opposite, and it does not imply that no license exists.

Unfortunately we are unable to share this license openly as it would mean a breach of several Enterprise Grade non-disclosure agreements.

In short, if you are interested in using this fine piece of software, you should contact the legal department of EnterpriseQualityCoding to have a custom-made Non-disclosure agreement written up for your particular use case, to allow negotiations to begin.
