### ISSUE TITLE
CNCF incubation? - KubeCon presentation - make it Cloud Native 

### ISSUE THREAD

**Issue by bodgergely** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#435]
Any future plans to make FizzBuzzEnterpriseEdition an incubation project under the of **Cloud Native Computing Foundation**?  [cncf](https://www.cncf.io/)

**Comment by wizzwizz4** [comment]
That says "non-profit", but we're a serious business for serious profit. Declined.
