### ISSUE TITLE
Refactor to Microservices architecture

### ISSUE THREAD

**Issue by bodgergely** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#438]
In 2019 it is deemed unacceptable to use a monolithic architecture.

**Comment by wizzwizz4** [comment]
It's not monolithic, it's just… statically linked. Yeah, that's it! It's statically linked. Each individual component functions independently of the others (except, of course, they need their dependencies, but that'd be the case in a traditional, old, boring microservices architecture too).

Non-technical explanation: The code is separated into different microservices which build upon each other to create the FizzBuzz implementation. We then compile them with static linking into the source code form we feed to the Java Virtual Machine's source-code interface.
