### ISSUE TITLE
k8s + kafka 

### ISSUE THREAD

**Issue by rowi1de** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#460]
Didn’t find any examples for federated multi-cloud vendor agnostic, IaC kubernetes deployments. Please add at least 17 yaml files, to be enterprisy.  

Scope creep: But what’s the estimate for integrating our “Fizz” and “Buzz” streams from Kafka ?

**Comment by Tylersuard** [comment]
From what I understand, the CTO has asked us to only invest time on republican, single-cloud vendor atheist squarebernetes software.  I like your suggestion though, we should definitely try to make this more enterprisy.
Recommending you for a promotion.
