### ISSUE TITLE
The coffee machine is (still) broken

### ISSUE THREAD

**Issue by blyxyas** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#576]
#561 Isn't being worked on!

**Comment by PurHur** [comment]
It is worked on https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition/pull/549 we just need some time to get company money,

**Comment by PurHur** [comment]
Wait what? 
See you at the coffee bar

**Comment by tigercoding56** [comment]
> It is worked on #549 we just need some time to get company money,

no you just need to create a more detailed issue , what is the  coffee machine license key subcontractor again
