### ISSUE TITLE
Not enough effort

### ISSUE THREAD

**Issue by ghost** [EnterpriseQualityCoding/FizzBuzzEnterpriseEdition#580]
Kind of seems like you guys half-assed this FizzBuzz program... do better. Weak.

**Comment by PurHur** [comment]
I cant speak for the company but we are working on it.
The pandemic hit us hard so we had to relocate all developers all over the world. I hope the team will be productive in 3-6 months from now on so we could ship a new release.

**Comment by ghost** [comment]
Sounds good, make sure you do so or else there shall be consequences.
